### PR TITLE
Added July hotfix

### PR DESCRIPTION
**Pull request by makamat**
Hotfix for July release includes a bug fix for when list of guides was not loading on HL.

### CODE REVIEW

**Comment by makamat** [comment]
@BryceHo - please schedule this to publish by Monday night (Aug 5). QA will verify this page in What's New panel of PC app after we push the latest build to store. Thank you!

**Comment by BryceHo** [comment]
Will do, Mahesh. Buckley (our Production Engineer) is back from vacation, so we can probably get the updated Docs page live shortly after the app updage goes live in the store. If that doesn’t happen until later this afternoon, I’ll ask Bishal in India to publish the doc page tonight.

**Comment by BryceHo** [comment]
Mahesh, here’s the review link: https://review.docs.microsoft.com/en-us/dynamics365/mixed-reality/guides/new?branch=master

I added one sentence at the end just to make it perfectly clear that you only need to update the app:

[cid:image003.jpg@01D54B88.CA958650]

Look OK?

**Comment by makamat** [comment]
Yes, looks good. Thank you Bryce.

**Pull request merged**
